const wordData = [
  
  { word: "社區", meaning: "community; neighborhood", example: "這個社區很安靜。(This community is very quiet.)" },
  { word: "白天", meaning: "daytime", example: "白天很熱，晚上才涼快。(It’s hot during the daytime and only cool at night.)" },
  { word: "被", meaning: "by (passive marker)", example: "他的手機被偷了。(His phone was stolen.)" },
  { word: "小偷", meaning: "thief", example: "小偷被警察抓到了。(The thief was caught by the police.)" },
  { word: "偷", meaning: "to steal", example: "有人偷了我的錢包。(Someone stole my wallet.)" },
  { word: "負責", meaning: "to be responsible for; in charge of", example: "她負責辦公室的文件。(She is responsible for the office documents.)" },
  { word: "安全", meaning: "safety; safe", example: "晚上回家要注意安全。(Be careful of your safety when going home at night.)" },
  { word: "大門", meaning: "main gate; front door", example: "學校大門在早上七點開。(The school’s main gate opens at 7 a.m.)" },
  { word: "草地", meaning: "lawn; grass field", example: "孩子們在草地上玩。(Children are playing on the lawn.)" },
  { word: "辦", meaning: "to hold; to organize; to handle", example: "我們要辦一個活動。(We are going to organize an event.)" },
  { word: "晴天", meaning: "sunny day", example: "今天是晴天，很適合出去走走。(Today is a sunny day, perfect for going out.)" },
  { word: "野餐", meaning: "picnic; to picnic", example: "我們星期天去公園野餐。(We’re going to the park for a picnic on Sunday.)" },
  { word: "餐", meaning: "meal", example: "這家飯店供應三餐。(This hotel serves three meals a day.)" },
  { word: "露營", meaning: "camping; to camp", example: "他們週末去山上露營。(They went camping in the mountains over the weekend.)" },
  { word: "雲", meaning: "cloud", example: "天空有很多白雲。(There are many white clouds in the sky.)" },
  { word: "躺", meaning: "to lie down", example: "他喜歡躺在沙發上看書。(He likes to lie on the sofa and read.)" },
  { word: "星星", meaning: "stars", example: "晚上可以看到很多星星。(You can see many stars at night.)" },
  { word: "感覺", meaning: "to feel; feeling", example: "我感覺今天會下雨。(I feel it’s going to rain today.)" },
  { word: "輕鬆", meaning: "relaxed; easy", example: "聽音樂讓我覺得很輕鬆。(Listening to music makes me feel relaxed.)" },
  { word: "睡著", meaning: "to fall asleep", example: "他太累了，很快就睡著了。(He was so tired that he fell asleep quickly.)" },
  { word: "陽光", meaning: "sunlight", example: "早上的陽光很溫暖。(The morning sunlight is warm.)" },
  { word: "香味", meaning: "fragrance; pleasant smell", example: "廚房裡傳來麵包的香味。(The smell of bread came from the kitchen.)" },
  { word: "座", meaning: "classifier for buildings, mountains, large objects", example: "山上有一座廟。(There is a temple on the mountain.)" },
  { word: "球場", meaning: "sports field; court", example: "我們在球場打籃球。(We played basketball on the court.)" },
  { word: "游泳池", meaning: "swimming pool", example: "這家飯店有游泳池。(This hotel has a swimming pool.)" },
  { word: "校友", meaning: "alumni", example: "他是我們學校的校友。(He is an alumnus of our school.)" },
  { word: "只要", meaning: "as long as; only need to", example: "只要努力，就會有結果。(As long as you work hard, you’ll get results.)" },
  { word: "請客", meaning: "to treat; to host a meal", example: "今天我生日，我請客！(It’s my birthday today — it’s my treat!)" },
  { word: "牛排", meaning: "steak", example: "他最喜歡吃牛排。(He loves eating steak.)" },
  { word: "紅綠燈", meaning: "traffic light", example: "過馬路要看紅綠燈。(Watch the traffic light when crossing the street.)" }
];
