const wordData = [
  
  { word: "社区", meaning: "community; neighborhood", example: "这个社区很安静。(This community is very quiet.)" },
  { word: "白天", meaning: "daytime", example: "白天很热，晚上才凉快。(It’s hot during the daytime and only cool at night.)" },
  { word: "被", meaning: "by (passive marker)", example: "他的手机被偷了。(His phone was stolen.)" },
  { word: "小偷", meaning: "thief", example: "小偷被警察抓到了。(The thief was caught by the police.)" },
  { word: "偷", meaning: "to steal", example: "有人偷了我的钱包。(Someone stole my wallet.)" },
  { word: "负责", meaning: "to be responsible for; in charge of", example: "她负责办公室的文件。(She is responsible for the office documents.)" },
  { word: "安全", meaning: "safety; safe", example: "晚上回家要注意安全。(Be careful of your safety when going home at night.)" },
  { word: "大门", meaning: "main gate; front door", example: "学校大门在早上七点开。(The school’s main gate opens at 7 a.m.)" },
  { word: "草地", meaning: "lawn; grass field", example: "孩子们在草地上玩。(Children are playing on the lawn.)" },
  { word: "办", meaning: "to hold; to organize; to handle", example: "我们要办一个活动。(We are going to organize an event.)" },
  { word: "晴天", meaning: "sunny day", example: "今天是晴天，很适合出去走走。(Today is a sunny day, perfect for going out.)" },
  { word: "野餐", meaning: "picnic; to picnic", example: "我们星期天去公园野餐。(We’re going to the park for a picnic on Sunday.)" },
  { word: "餐", meaning: "meal", example: "这家饭店供应三餐。(This hotel serves three meals a day.)" },
  { word: "露营", meaning: "camping; to camp", example: "他们週末去山上露营。(They went camping in the mountains over the weekend.)" },
  { word: "云", meaning: "cloud", example: "天空有很多白云。(There are many white clouds in the sky.)" },
  { word: "躺", meaning: "to lie down", example: "他喜欢躺在沙发上看书。(He likes to lie on the sofa and read.)" },
  { word: "星星", meaning: "stars", example: "晚上可以看到很多星星。(You can see many stars at night.)" },
  { word: "感觉", meaning: "to feel; feeling", example: "我感觉今天会下雨。(I feel it’s going to rain today.)" },
  { word: "轻松", meaning: "relaxed; easy", example: "听音乐让我觉得很轻松。(Listening to music makes me feel relaxed.)" },
  { word: "睡着", meaning: "to fall asleep", example: "他太累了，很快就睡着了。(He was so tired that he fell asleep quickly.)" },
  { word: "阳光", meaning: "sunlight", example: "早上的阳光很温暖。(The morning sunlight is warm.)" },
  { word: "香味", meaning: "fragrance; pleasant smell", example: "厨房里传来麵包的香味。(The smell of bread came from the kitchen.)" },
  { word: "座", meaning: "classifier for buildings, mountains, large objects", example: "山上有一座庙。(There is a temple on the mountain.)" },
  { word: "球场", meaning: "sports field; court", example: "我们在球场打篮球。(We played basketball on the court.)" },
  { word: "游泳池", meaning: "swimming pool", example: "这家饭店有游泳池。(This hotel has a swimming pool.)" },
  { word: "校友", meaning: "alumni", example: "他是我们学校的校友。(He is an alumnus of our school.)" },
  { word: "只要", meaning: "as long as; only need to", example: "只要努力，就会有结果。(As long as you work hard, you’ll get results.)" },
  { word: "请客", meaning: "to treat; to host a meal", example: "今天我生日，我请客！(It’s my birthday today — it’s my treat!)" },
  { word: "牛排", meaning: "steak", example: "他最喜欢吃牛排。(He loves eating steak.)" },
  { word: "红绿灯", meaning: "traffic light", example: "过马路要看红绿灯。(Watch the traffic light when crossing the street.)" }
];

